In [53]:
from pathlib import Path
import pandas as pd

photo_folder = Path("C:/Users/omistaja/Desktop/AS Project/Data/Photos/S0001b")

files = list(photo_folder.glob("*"))

records = []

for file in files:
    records.append({
        "filename": file.name,
        "path": str(file)
    })

import re
import pandas as pd

manifest = pd.DataFrame(records)

manifest.head(445)

                  filename                                               path
0   SG0031_O0031_P0054.JPG  C:\Users\omistaja\Desktop\AS Project\Data\Phot...
1   SG0032_O0032_P0055.JPG  C:\Users\omistaja\Desktop\AS Project\Data\Phot...
2   SG0033_O0033_P0056.JPG  C:\Users\omistaja\Desktop\AS Project\Data\Phot...
3   SG0034_O0034_P0057.JPG  C:\Users\omistaja\Desktop\AS Project\Data\Phot...
4   SG0035_O0035_P0058.JPG  C:\Users\omistaja\Desktop\AS Project\Data\Phot...
5   SG0036_O0036_P0059.JPG  C:\Users\omistaja\Desktop\AS Project\Data\Phot...
6   SG0037_O0037_P0060.JPG  C:\Users\omistaja\Desktop\AS Project\Data\Phot...
7   SG0038_O0038_P0061.JPG  C:\Users\omistaja\Desktop\AS Project\Data\Phot...
8   SG0039_O0039_P0062.JPG  C:\Users\omistaja\Desktop\AS Project\Data\Phot...
9   SG0041_O0041_P0064.JPG  C:\Users\omistaja\Desktop\AS Project\Data\Phot...
10  SG0042_O0042_P0065.JPG  C:\Users\omistaja\Desktop\AS Project\Data\Phot...
11  SG0043_O0043_P0066.JPG  C:\Users\omistaja\Desktop\AS Project\Data\Phot...
12  SG0048_O0048_P0071.JPG  C:\Users\omistaja\Desktop\AS Project\Data\Phot...
13  SG0049_O0049_P0072.JPG  C:\Users\omistaja\Desktop\AS Project\Data\Phot...
14  SG0050_O0050_P0073.JPG  C:\Users\omistaja\Desktop\AS Project\Data\Phot...
15  SG0051_O0051_P0074.JPG  C:\Users\omistaja\Desktop\AS Project\Data\Phot...
16  SG0052_O0052_P0075.JPG  C:\Users\omistaja\Desktop\AS Project\Data\Phot...

In [54]:
import pandas as pd

manifest = pd.DataFrame({
    "path": files
})

manifest["filename"] = manifest["path"].apply(
    lambda x: x.name
)

manifest.head(445)

manifest.to_csv("Filenames")

In [55]:
test_file = manifest.iloc[0]["path"]

print(test_file)

C:\Users\omistaja\Desktop\AS Project\Data\Photos\S0001b\SG0031_O0031_P0054.JPG

In [56]:
from PIL import Image
from PIL.ExifTags import TAGS

with Image.open(test_file) as img:
    exif = img.getexif()

    print("Number of EXIF fields:", len(exif))

    for tag_id, value in exif.items():
        tag = TAGS.get(tag_id, tag_id)
        print(tag, ":", value)

Number of EXIF fields: 12
GPSInfo : 9300
ResolutionUnit : 2
ExifOffset : 360
Make : Canon
Model : Canon EOS 100D
YResolution : 72.0
Orientation : 8
DateTime : 2026:08:16 11:01:26
YCbCrPositioning : 2
Copyright :
XResolution : 72.0
Artist :

In [57]:
from PIL import Image
from PIL.ExifTags import IFD
import pandas as pd

def get_timestamp(file_path):
    try:
        with Image.open(file_path) as img:
            exif = img.getexif()

            exif_ifd = exif.get_ifd(IFD.Exif)

            timestamp = exif_ifd.get(36867)

            return timestamp

    except Exception:
        return None

In [58]:
manifest["capture_datetime_original"] = (
    manifest["path"].apply(get_timestamp)
)

manifest

,path,filename,capture_datetime_original
0,C:\Users\omistaja\Desktop\AS Project\Data\Phot...,SG0031_O0031_P0054.JPG,2026:08:16 11:01:26
1,C:\Users\omistaja\Desktop\AS Project\Data\Phot...,SG0032_O0032_P0055.JPG,2026:08:16 11:04:07
2,C:\Users\omistaja\Desktop\AS Project\Data\Phot...,SG0033_O0033_P0056.JPG,2026:08:16 11:05:20
3,C:\Users\omistaja\Desktop\AS Project\Data\Phot...,SG0034_O0034_P0057.JPG,2026:08:16 11:06:51
4,C:\Users\omistaja\Desktop\AS Project\Data\Phot...,SG0035_O0035_P0058.JPG,2026:08:16 11:07:09
5,C:\Users\omistaja\Desktop\AS Project\Data\Phot...,SG0036_O0036_P0059.JPG,2026:08:16 11:07:26
6,C:\Users\omistaja\Desktop\AS Project\Data\Phot...,SG0037_O0037_P0060.JPG,2026:08:16 11:09:23
7,C:\Users\omistaja\Desktop\AS Project\Data\Phot...,SG0038_O0038_P0061.JPG,2026:08:16 11:09:35
8,C:\Users\omistaja\Desktop\AS Project\Data\Phot...,SG0039_O0039_P0062.JPG,2026:08:16 11:11:22
9,C:\Users\omistaja\Desktop\AS Project\Data\Phot...,SG0041_O0041_P0064.JPG,2026:08:16 11:12:07
10,C:\Users\omistaja\Desktop\AS Project\Data\Phot...,SG0042_O0042_P0065.JPG,2026:08:16 11:13:29
11,C:\Users\omistaja\Desktop\AS Project\Data\Phot...,SG0043_O0043_P0066.JPG,2026:08:16 11:14:55
12,C:\Users\omistaja\Desktop\AS Project\Data\Phot...,SG0048_O0048_P0071.JPG,2026:08:16 11:22:32
13,C:\Users\omistaja\Desktop\AS Project\Data\Phot...,SG0049_O0049_P0072.JPG,2026:08:16 11:24:03
14,C:\Users\omistaja\Desktop\AS Project\Data\Phot...,SG0050_O0050_P0073.JPG,2026:08:16 11:24:13
15,C:\Users\omistaja\Desktop\AS Project\Data\Phot...,SG0051_O0051_P0074.JPG,2026:08:16 11:25:20
16,C:\Users\omistaja\Desktop\AS Project\Data\Phot...,SG0052_O0052_P0075.JPG,2026:08:16 11:25:33

In [59]:
manifest["capture_datetime_original"] = pd.to_datetime(
    manifest["capture_datetime_original"],
    format="%Y:%m:%d %H:%M:%S",
    errors="coerce"
)

manifest[
    ["filename", "capture_datetime_original"]
].head(10)

camera_offset_hours = 5

manifest["capture_datetime_corrected"] = (
    manifest["capture_datetime_original"]
    + pd.Timedelta(hours=camera_offset_hours)
)

manifest[
    [
        "filename",
        "capture_datetime_original",
        "capture_datetime_corrected"
    ]
].head(1500)

manifest.to_csv("S0002_photo_timestamps_corrected")

In [8]:
%pip install gpxpy

Requirement already satisfied: gpxpy in c:\users\omistaja\anaconda3\lib\site-packages (1.6.2)
Note: you may need to restart the kernel to use updated packages.

In [60]:
from pathlib import Path
import gpxpy
import pandas as pd

gpx_path = Path(
    "C:/Users/omistaja/Desktop/AS Project/Data/Comaps/Xinshi_Township_08162026_S0001b.gpx"
)

with open(gpx_path, "r", encoding="utf-8") as gpx_file:
    gpx = gpxpy.parse(gpx_file)

track_points = []

for track in gpx.tracks:
    for segment in track.segments:
        for point in segment.points:
            track_points.append({
                "gpx_time": point.time,
                "latitude": point.latitude,
                "longitude": point.longitude,
                "elevation": point.elevation
            })

gpx_df = pd.DataFrame(track_points)

gpx_df["gpx_time_taiwan"] = (
    pd.to_datetime(gpx_df["gpx_time"], utc=True)
    .dt.tz_convert("Asia/Taipei")
)

gpx_df["gpx_time_local"] = (
    gpx_df["gpx_time_taiwan"]
    .dt.tz_localize(None)
)

gpx_df.head(600)

,gpx_time,latitude,longitude,elevation,gpx_time_taiwan,gpx_time_local
0,2026-08-16 08:03:10+00:00,23.103176,120.28576,9.0,2026-08-16 16:03:10+08:00,2026-08-16 16:03:10
1,2026-08-16 08:03:21+00:00,23.103178,120.28587,11.0,2026-08-16 16:03:21+08:00,2026-08-16 16:03:21
2,2026-08-16 08:03:29+00:00,23.103202,120.28597,11.0,2026-08-16 16:03:29+08:00,2026-08-16 16:03:29
3,2026-08-16 08:03:41+00:00,23.103223,120.28609,11.0,2026-08-16 16:03:41+08:00,2026-08-16 16:03:41
4,2026-08-16 08:03:57+00:00,23.103243,120.28619,11.0,2026-08-16 16:03:57+08:00,2026-08-16 16:03:57
5,2026-08-16 08:04:07+00:00,23.103260,120.28631,11.0,2026-08-16 16:04:07+08:00,2026-08-16 16:04:07
6,2026-08-16 08:04:16+00:00,23.103285,120.28642,10.0,2026-08-16 16:04:16+08:00,2026-08-16 16:04:16
7,2026-08-16 08:07:11+00:00,23.103368,120.28649,11.0,2026-08-16 16:07:11+08:00,2026-08-16 16:07:11
8,2026-08-16 08:08:53+00:00,23.103337,120.28659,11.0,2026-08-16 16:08:53+08:00,2026-08-16 16:08:53
9,2026-08-16 08:09:01+00:00,23.103349,120.28670,11.0,2026-08-16 16:09:01+08:00,2026-08-16 16:09:01
10,2026-08-16 08:09:09+00:00,23.103391,120.28681,11.0,2026-08-16 16:09:09+08:00,2026-08-16 16:09:09
11,2026-08-16 08:09:19+00:00,23.103440,120.28691,11.0,2026-08-16 16:09:19+08:00,2026-08-16 16:09:19
12,2026-08-16 08:09:29+00:00,23.103454,120.28702,11.0,2026-08-16 16:09:29+08:00,2026-08-16 16:09:29
13,2026-08-16 08:11:33+00:00,23.103498,120.28712,10.0,2026-08-16 16:11:33+08:00,2026-08-16 16:11:33
14,2026-08-16 08:11:46+00:00,23.103502,120.28723,10.0,2026-08-16 16:11:46+08:00,2026-08-16 16:11:46
15,2026-08-16 08:12:01+00:00,23.103470,120.28734,10.0,2026-08-16 16:12:01+08:00,2026-08-16 16:12:01
16,2026-08-16 08:12:09+00:00,23.103495,120.28744,10.0,2026-08-16 16:12:09+08:00,2026-08-16 16:12:09
17,2026-08-16 08:15:16+00:00,23.103563,120.28759,11.0,2026-08-16 16:15:16+08:00,2026-08-16 16:15:16
18,2026-08-16 08:16:59+00:00,23.103581,120.28769,11.0,2026-08-16 16:16:59+08:00,2026-08-16 16:16:59
19,2026-08-16 08:17:07+00:00,23.103583,120.28781,11.0,2026-08-16 16:17:07+08:00,2026-08-16 16:17:07
20,2026-08-16 08:17:15+00:00,23.103601,120.28791,12.0,2026-08-16 16:17:15+08:00,2026-08-16 16:17:15
21,2026-08-16 08:17:24+00:00,23.103639,120.28800,12.0,2026-08-16 16:17:24+08:00,2026-08-16 16:17:24
22,2026-08-16 08:18:25+00:00,23.103662,120.28810,12.0,2026-08-16 16:18:25+08:00,2026-08-16 16:18:25
23,2026-08-16 08:18:54+00:00,23.103641,120.28821,12.0,2026-08-16 16:18:54+08:00,2026-08-16 16:18:54
24,2026-08-16 08:19:02+00:00,23.103657,120.28831,13.0,2026-08-16 16:19:02+08:00,2026-08-16 16:19:02
25,2026-08-16 08:19:12+00:00,23.103686,120.28842,12.0,2026-08-16 16:19:12+08:00,2026-08-16 16:19:12
26,2026-08-16 08:19:20+00:00,23.103702,120.28854,13.0,2026-08-16 16:19:20+08:00,2026-08-16 16:19:20
27,2026-08-16 08:19:30+00:00,23.103723,120.28866,13.0,2026-08-16 16:19:30+08:00,2026-08-16 16:19:30
28,2026-08-16 08:19:39+00:00,23.103772,120.28876,13.0,2026-08-16 16:19:39+08:00,2026-08-16 16:19:39
29,2026-08-16 08:20:31+00:00,23.103810,120.28885,13.0,2026-08-16 16:20:31+08:00,2026-08-16 16:20:31
30,2026-08-16 08:20:50+00:00,23.103867,120.28894,13.0,2026-08-16 16:20:50+08:00,2026-08-16 16:20:50
31,2026-08-16 08:21:59+00:00,23.103863,120.28906,12.0,2026-08-16 16:21:59+08:00,2026-08-16 16:21:59
32,2026-08-16 08:22:08+00:00,23.103896,120.28916,12.0,2026-08-16 16:22:08+08:00,2026-08-16 16:22:08
33,2026-08-16 08:23:00+00:00,23.103904,120.28927,13.0,2026-08-16 16:23:00+08:00,2026-08-16 16:23:00
34,2026-08-16 08:25:08+00:00,23.103945,120.28940,13.0,2026-08-16 16:25:08+08:00,2026-08-16 16:25:08

In [61]:
manifest[
    ["filename", "capture_datetime_corrected"]
].head(20)

                  filename capture_datetime_corrected
0   SG0031_O0031_P0054.JPG        2026-08-16 16:01:26
1   SG0032_O0032_P0055.JPG        2026-08-16 16:04:07
2   SG0033_O0033_P0056.JPG        2026-08-16 16:05:20
3   SG0034_O0034_P0057.JPG        2026-08-16 16:06:51
4   SG0035_O0035_P0058.JPG        2026-08-16 16:07:09
5   SG0036_O0036_P0059.JPG        2026-08-16 16:07:26
6   SG0037_O0037_P0060.JPG        2026-08-16 16:09:23
7   SG0038_O0038_P0061.JPG        2026-08-16 16:09:35
8   SG0039_O0039_P0062.JPG        2026-08-16 16:11:22
9   SG0041_O0041_P0064.JPG        2026-08-16 16:12:07
10  SG0042_O0042_P0065.JPG        2026-08-16 16:13:29
11  SG0043_O0043_P0066.JPG        2026-08-16 16:14:55
12  SG0048_O0048_P0071.JPG        2026-08-16 16:22:32
13  SG0049_O0049_P0072.JPG        2026-08-16 16:24:03
14  SG0050_O0050_P0073.JPG        2026-08-16 16:24:13
15  SG0051_O0051_P0074.JPG        2026-08-16 16:25:20
16  SG0052_O0052_P0075.JPG        2026-08-16 16:25:33

In [62]:
gpx_df[
    ["gpx_time_taiwan", "latitude", "longitude"]
].head(445)

             gpx_time_taiwan   latitude  longitude
0  2026-08-16 16:03:10+08:00  23.103176  120.28576
1  2026-08-16 16:03:21+08:00  23.103178  120.28587
2  2026-08-16 16:03:29+08:00  23.103202  120.28597
3  2026-08-16 16:03:41+08:00  23.103223  120.28609
4  2026-08-16 16:03:57+08:00  23.103243  120.28619
5  2026-08-16 16:04:07+08:00  23.103260  120.28631
6  2026-08-16 16:04:16+08:00  23.103285  120.28642
7  2026-08-16 16:07:11+08:00  23.103368  120.28649
8  2026-08-16 16:08:53+08:00  23.103337  120.28659
9  2026-08-16 16:09:01+08:00  23.103349  120.28670
10 2026-08-16 16:09:09+08:00  23.103391  120.28681
11 2026-08-16 16:09:19+08:00  23.103440  120.28691
12 2026-08-16 16:09:29+08:00  23.103454  120.28702
13 2026-08-16 16:11:33+08:00  23.103498  120.28712
14 2026-08-16 16:11:46+08:00  23.103502  120.28723
15 2026-08-16 16:12:01+08:00  23.103470  120.28734
16 2026-08-16 16:12:09+08:00  23.103495  120.28744
17 2026-08-16 16:15:16+08:00  23.103563  120.28759
18 2026-08-16 16:16:59+08:00  23.103581  120.28769
19 2026-08-16 16:17:07+08:00  23.103583  120.28781
20 2026-08-16 16:17:15+08:00  23.103601  120.28791
21 2026-08-16 16:17:24+08:00  23.103639  120.28800
22 2026-08-16 16:18:25+08:00  23.103662  120.28810
23 2026-08-16 16:18:54+08:00  23.103641  120.28821
24 2026-08-16 16:19:02+08:00  23.103657  120.28831
25 2026-08-16 16:19:12+08:00  23.103686  120.28842
26 2026-08-16 16:19:20+08:00  23.103702  120.28854
27 2026-08-16 16:19:30+08:00  23.103723  120.28866
28 2026-08-16 16:19:39+08:00  23.103772  120.28876
29 2026-08-16 16:20:31+08:00  23.103810  120.28885
30 2026-08-16 16:20:50+08:00  23.103867  120.28894
31 2026-08-16 16:21:59+08:00  23.103863  120.28906
32 2026-08-16 16:22:08+08:00  23.103896  120.28916
33 2026-08-16 16:23:00+08:00  23.103904  120.28927
34 2026-08-16 16:25:08+08:00  23.103945  120.28940

In [63]:
manifest = manifest.sort_values(
    "capture_datetime_corrected"
).reset_index(drop=True)

gpx_df = gpx_df.sort_values(
    "gpx_time_local"
).reset_index(drop=True)

matched = pd.merge_asof(
    manifest,
    gpx_df[
        ["gpx_time_local", "latitude", "longitude"]
    ],
    left_on="capture_datetime_corrected",
    right_on="gpx_time_local",
    direction="nearest"
)

matched.head(445)

matched.to_csv("Photo coordinates2")

In [13]:
matched["time_difference_seconds"] = (
    matched["capture_datetime_corrected"]
    - matched["gpx_time_local"]
).abs().dt.total_seconds()

matched[
    [
        "filename",
        "capture_datetime_corrected",
        "gpx_time_local",
        "time_difference_seconds",
        "latitude",
        "longitude"
    ]
].head(20)

matched["time_difference_seconds"].describe()

matched["gpx_match_status"] = matched["time_difference_seconds"].apply(
    lambda x: "good" if x <= 30 else "review"
)

matched["gpx_match_status"].value_counts()

gpx_match_status
good      323
review    122
Name: count, dtype: int64

In [14]:
matched["time_difference_seconds"].describe()

pd.cut(
    matched["time_difference_seconds"],
    bins=[0, 5, 10, 30, 60, 120, 300, float("inf")],
    include_lowest=True
).value_counts().sort_index()

time_difference_seconds
(-0.001, 5.0]     109
(5.0, 10.0]        77
(10.0, 30.0]      137
(30.0, 60.0]       74
(60.0, 120.0]      41
(120.0, 300.0]      5
(300.0, inf]        2
Name: count, dtype: int64

In [15]:
matched[
    [
        "filename",
        "capture_datetime_corrected",
        "gpx_time_local",
        "time_difference_seconds",
        "latitude",
        "longitude"
    ]
].sort_values(
    "time_difference_seconds",
    ascending=False
).head(30)

,filename,capture_datetime_corrected,gpx_time_local,time_difference_seconds,latitude,longitude
0,IMG_0659.JPG,2026-08-18 12:56:10,2026-08-18 13:02:47,397.0,24.847607,121.55125
1,IMG_0660.JPG,2026-08-18 12:56:22,2026-08-18 13:02:47,385.0,24.847607,121.55125
2,IMG_0665.JPG,2026-08-18 12:58:50,2026-08-18 13:02:47,237.0,24.847607,121.55125
3,IMG_0666.JPG,2026-08-18 12:59:01,2026-08-18 13:02:47,226.0,24.847607,121.55125
4,IMG_0668.JPG,2026-08-18 13:00:03,2026-08-18 13:02:47,164.0,24.847607,121.55125
5,IMG_0669.JPG,2026-08-18 13:00:04,2026-08-18 13:02:47,163.0,24.847607,121.55125
134,IMG_0825.JPG,2026-08-18 13:39:51,2026-08-18 13:37:45,126.0,24.848721,121.55170
133,IMG_0824.JPG,2026-08-18 13:39:45,2026-08-18 13:37:45,120.0,24.848721,121.55170
135,IMG_0826.JPG,2026-08-18 13:41:09,2026-08-18 13:43:09,120.0,24.848801,121.55180
27,IMG_0706.JPG,2026-08-18 13:14:41,2026-08-18 13:12:46,115.0,24.847857,121.55138
132,IMG_0823.JPG,2026-08-18 13:39:37,2026-08-18 13:37:45,112.0,24.848721,121.55170
91,IMG_0782.JPG,2026-08-18 13:31:42,2026-08-18 13:33:34,112.0,24.848437,121.55183
154,IMG_0851.JPG,2026-08-18 13:47:58,2026-08-18 13:46:22,96.0,24.848869,121.55186
155,IMG_0852.JPG,2026-08-18 13:48:04,2026-08-18 13:49:37,93.0,24.848993,121.55183
72,IMG_0759.JPG,2026-08-18 13:26:10,2026-08-18 13:27:41,91.0,24.848379,121.55159
92,IMG_0784.JPG,2026-08-18 13:32:04,2026-08-18 13:33:34,90.0,24.848437,121.55183
382,IMG_1092.JPG,2026-08-18 15:03:28,2026-08-18 15:02:06,82.0,24.860627,121.55158
153,IMG_0850.JPG,2026-08-18 13:47:43,2026-08-18 13:46:22,81.0,24.848869,121.55186
73,IMG_0760.JPG,2026-08-18 13:26:21,2026-08-18 13:27:41,80.0,24.848379,121.55159
383,IMG_1093.JPG,2026-08-18 15:03:31,2026-08-18 15:04:51,80.0,24.860774,121.55164
381,IMG_1091.JPG,2026-08-18 15:03:24,2026-08-18 15:02:06,78.0,24.860627,121.55158
93,IMG_0785.JPG,2026-08-18 13:32:16,2026-08-18 13:33:34,78.0,24.848437,121.55183
136,IMG_0827.JPG,2026-08-18 13:41:52,2026-08-18 13:43:09,77.0,24.848801,121.55180
131,IMG_0822.JPG,2026-08-18 13:39:02,2026-08-18 13:37:45,77.0,24.848721,121.55170
245,IMG_0953.JPG,2026-08-18 14:33:08,2026-08-18 14:31:53,75.0,24.856204,121.55168
400,IMG_1112.JPG,2026-08-18 15:06:40,2026-08-18 15:05:26,74.0,24.860971,121.55163
380,IMG_1090.JPG,2026-08-18 15:03:18,2026-08-18 15:02:06,72.0,24.860627,121.55158
399,IMG_1111.JPG,2026-08-18 15:06:38,2026-08-18 15:05:26,72.0,24.860971,121.55163
244,IMG_0952.JPG,2026-08-18 14:33:04,2026-08-18 14:31:53,71.0,24.856204,121.55168
6,IMG_0676.JPG,2026-08-18 13:01:37,2026-08-18 13:02:47,70.0,24.847607,121.55125

In [123]:
target_time = pd.Timestamp("2026-08-18 07:58:50")

closest = gpx_df.iloc[
    (gpx_df["gpx_time_local"] - target_time)
    .abs()
    .argsort()[:1]
]

closest[
    ["gpx_time_local", "latitude", "longitude"]
]

       gpx_time_local   latitude  longitude
0 2026-08-18 13:02:47  24.847607  121.55125